/* This file was generated by syncqt. */
#ifndef QT_QT3DEXTRAS_VERSION_H
#define QT_QT3DEXTRAS_VERSION_H

#define QT3DEXTRAS_VERSION_STR "6.5.0"

#define QT3DEXTRAS_VERSION 0x060500

#endif // QT_QT3DEXTRAS_VERSION_H
